# Generated by Django 5.1 on 2024-08-08 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=150, verbose_name='место')),
                ('time', models.TimeField(verbose_name='время когда выполнить привычку')),
                ('action', models.CharField(max_length=150, verbose_name='действие')),
                ('nice_habit', models.BooleanField(choices=[(True, 'Приятная'), (False, 'Нет')], default=True, verbose_name='приятная привычка')),
                ('periodicity', models.BooleanField(choices=[(True, 'Ежедневная'), (False, 'Еженедельная')], default=True, verbose_name='периодичность')),
                ('prize', models.CharField(blank=True, max_length=100, null=True, verbose_name='вознаграждение')),
                ('duration', models.SmallIntegerField(verbose_name='Продолжительность в минутах')),
                ('is_public', models.BooleanField(choices=[(True, 'Публичная'), (False, 'Приватная')], default=False, verbose_name='признак публичности')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
                ('related', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.habit', verbose_name='связанная привычка')),
            ],
            options={
                'verbose_name': 'привычка',
                'verbose_name_plural': 'привычки',
                'ordering': ['-id'],
            },
        ),
    ]
